on:
  pull_request:
    # run in each PR in this repo
    branches: '**'
  push:
    branches: '**'

name: check-current

jobs:
  R-code-check:
    runs-on: ${{ matrix.config.os }}

    continue-on-error: ${{ matrix.config.allowfail }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel',   allowfail: false}
          - {os: macOS-latest,   r: 'release', allowfail: false}
          - {os: macOS-latest,   r: 'oldrel', allowfail: false}
          - {os: ubuntu-latest,  r: 'devel',   allowfail: false}
          - {os: ubuntu-latest,  r: 'release', allowfail: false}
          - {os: ubuntu-latest,  r: 'oldrel', allowfail: false}
          - {os: windows-latest, r: 'devel',   allowfail: false}
          - {os: windows-latest, r: 'release', allowfail: false}
          - {os: windows-latest, r: 'oldrel', allowfail: false}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          # use RStudio Package Manager to quickly install packages
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_LENGTH_1_CONDITION_: verbose
          _R_CHECK_LENGTH_1_LOGIC2_: verbose
